#!/bin/sh

# set python version
: ${PYTHON_VERSION:='python3.10'}

# gather filesystem information
DOCKER_BUILD_SCRIPT=$(realpath $0)
DOCKER_BUILD_DIR=$(realpath $(dirname DOCKER_BUILD_SCRIPT))
DOCKERFILE=$DOCKER_BUILD_DIR/Dockerfile
CTC_REPO=$(dirname $(dirname $DOCKER_BUILD_DIR))

# print summary
echo "running build script:" $DOCKER_BUILD_SCRIPT
echo "using Dockerfile:" $DOCKERFILE
echo "using repository:" $CTC_REPO
echo "using python version:" $PYTHON_VERSION

# build image
export DOCKER_BUILDKIT=1
docker build \
    -f $DOCKERFILE \
    -t ctc/ctc-$PYTHON_VERSION \
    --build-arg PYTHON_VERSION=$PYTHON_VERSION \
    $CTC_REPO
    #--no-cache \

