ctoken_function_abis = {
    '_setImplementation': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'address',
                'name': 'implementation_',
                'type': 'address',
            },
            {'internalType': 'bool', 'name': 'allowResign', 'type': 'bool'},
            {
                'internalType': 'bytes',
                'name': 'becomeImplementationData',
                'type': 'bytes',
            },
        ],
        'name': '_setImplementation',
        'outputs': [],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'admin': {
        'constant': True,
        'inputs': [],
        'name': 'admin',
        'outputs': [
            {'internalType': 'address payable', 'name': '', 'type': 'address'}
        ],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'adminHasRights': {
        'constant': True,
        'inputs': [],
        'name': 'adminHasRights',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'delegateToImplementation': {
        'constant': False,
        'inputs': [{'internalType': 'bytes', 'name': 'data', 'type': 'bytes'}],
        'name': 'delegateToImplementation',
        'outputs': [{'internalType': 'bytes', 'name': '', 'type': 'bytes'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'fuseAdminHasRights': {
        'constant': True,
        'inputs': [],
        'name': 'fuseAdminHasRights',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'implementation': {
        'constant': True,
        'inputs': [],
        'name': 'implementation',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    '_acceptAdmin': {
        'constant': False,
        'inputs': [],
        'name': '_acceptAdmin',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_addReserves': {
        'constant': False,
        'inputs': [
            {'internalType': 'uint256', 'name': 'addAmount', 'type': 'uint256'}
        ],
        'name': '_addReserves',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_becomeImplementation': {
        'constant': False,
        'inputs': [{'internalType': 'bytes', 'name': 'data', 'type': 'bytes'}],
        'name': '_becomeImplementation',
        'outputs': [],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_reduceReserves': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'reduceAmount',
                'type': 'uint256',
            }
        ],
        'name': '_reduceReserves',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_renounceAdminRights': {
        'constant': False,
        'inputs': [],
        'name': '_renounceAdminRights',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_renounceFuseAdminRights': {
        'constant': False,
        'inputs': [],
        'name': '_renounceFuseAdminRights',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_resignImplementation': {
        'constant': False,
        'inputs': [],
        'name': '_resignImplementation',
        'outputs': [],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_setAdminFee': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'newAdminFeeMantissa',
                'type': 'uint256',
            }
        ],
        'name': '_setAdminFee',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_setComptroller': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'contract ComptrollerInterface',
                'name': 'newComptroller',
                'type': 'address',
            }
        ],
        'name': '_setComptroller',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_setFuseFee': {
        'constant': False,
        'inputs': [],
        'name': '_setFuseFee',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_setInterestRateModel': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'contract InterestRateModel',
                'name': 'newInterestRateModel',
                'type': 'address',
            }
        ],
        'name': '_setInterestRateModel',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_setPendingAdmin': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'address payable',
                'name': 'newPendingAdmin',
                'type': 'address',
            }
        ],
        'name': '_setPendingAdmin',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_setReserveFactor': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'newReserveFactorMantissa',
                'type': 'uint256',
            }
        ],
        'name': '_setReserveFactor',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_withdrawAdminFees': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'withdrawAmount',
                'type': 'uint256',
            }
        ],
        'name': '_withdrawAdminFees',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    '_withdrawFuseFees': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'withdrawAmount',
                'type': 'uint256',
            }
        ],
        'name': '_withdrawFuseFees',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'accrualBlockNumber': {
        'constant': True,
        'inputs': [],
        'name': 'accrualBlockNumber',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'accrueInterest': {
        'constant': False,
        'inputs': [],
        'name': 'accrueInterest',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'adminFeeMantissa': {
        'constant': True,
        'inputs': [],
        'name': 'adminFeeMantissa',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'allowance': {
        'constant': True,
        'inputs': [
            {'internalType': 'address', 'name': 'owner', 'type': 'address'},
            {'internalType': 'address', 'name': 'spender', 'type': 'address'},
        ],
        'name': 'allowance',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'approve': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'spender', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
        ],
        'name': 'approve',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'balanceOf': {
        'constant': True,
        'inputs': [
            {'internalType': 'address', 'name': 'owner', 'type': 'address'}
        ],
        'name': 'balanceOf',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'balanceOfUnderlying': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'owner', 'type': 'address'}
        ],
        'name': 'balanceOfUnderlying',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'borrow': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'borrowAmount',
                'type': 'uint256',
            }
        ],
        'name': 'borrow',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'borrowBalanceCurrent': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'account', 'type': 'address'}
        ],
        'name': 'borrowBalanceCurrent',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'borrowBalanceStored': {
        'constant': True,
        'inputs': [
            {'internalType': 'address', 'name': 'account', 'type': 'address'}
        ],
        'name': 'borrowBalanceStored',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'borrowIndex': {
        'constant': True,
        'inputs': [],
        'name': 'borrowIndex',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'borrowRatePerBlock': {
        'constant': True,
        'inputs': [],
        'name': 'borrowRatePerBlock',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'comptroller': {
        'constant': True,
        'inputs': [],
        'name': 'comptroller',
        'outputs': [
            {
                'internalType': 'contract ComptrollerInterface',
                'name': '',
                'type': 'address',
            }
        ],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'decimals': {
        'constant': True,
        'inputs': [],
        'name': 'decimals',
        'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'exchangeRateCurrent': {
        'constant': False,
        'inputs': [],
        'name': 'exchangeRateCurrent',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'exchangeRateStored': {
        'constant': True,
        'inputs': [],
        'name': 'exchangeRateStored',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'fuseFeeMantissa': {
        'constant': True,
        'inputs': [],
        'name': 'fuseFeeMantissa',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'getAccountSnapshot': {
        'constant': True,
        'inputs': [
            {'internalType': 'address', 'name': 'account', 'type': 'address'}
        ],
        'name': 'getAccountSnapshot',
        'outputs': [
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
        ],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'getCash': {
        'constant': True,
        'inputs': [],
        'name': 'getCash',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'initialize': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'address',
                'name': 'underlying_',
                'type': 'address',
            },
            {
                'internalType': 'contract ComptrollerInterface',
                'name': 'comptroller_',
                'type': 'address',
            },
            {
                'internalType': 'contract InterestRateModel',
                'name': 'interestRateModel_',
                'type': 'address',
            },
            {
                'internalType': 'uint256',
                'name': 'initialExchangeRateMantissa_',
                'type': 'uint256',
            },
            {'internalType': 'string', 'name': 'name_', 'type': 'string'},
            {'internalType': 'string', 'name': 'symbol_', 'type': 'string'},
            {'internalType': 'uint8', 'name': 'decimals_', 'type': 'uint8'},
            {
                'internalType': 'uint256',
                'name': 'reserveFactorMantissa_',
                'type': 'uint256',
            },
            {
                'internalType': 'uint256',
                'name': 'adminFeeMantissa_',
                'type': 'uint256',
            },
        ],
        'name': 'initialize',
        'outputs': [],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'interestRateModel': {
        'constant': True,
        'inputs': [],
        'name': 'interestRateModel',
        'outputs': [
            {
                'internalType': 'contract InterestRateModel',
                'name': '',
                'type': 'address',
            }
        ],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'isCEther': {
        'constant': True,
        'inputs': [],
        'name': 'isCEther',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'isCToken': {
        'constant': True,
        'inputs': [],
        'name': 'isCToken',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'liquidateBorrow': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'borrower', 'type': 'address'},
            {
                'internalType': 'uint256',
                'name': 'repayAmount',
                'type': 'uint256',
            },
            {
                'internalType': 'contract CTokenInterface',
                'name': 'cTokenCollateral',
                'type': 'address',
            },
        ],
        'name': 'liquidateBorrow',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'mint': {
        'constant': False,
        'inputs': [
            {'internalType': 'uint256', 'name': 'mintAmount', 'type': 'uint256'}
        ],
        'name': 'mint',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'name': {
        'constant': True,
        'inputs': [],
        'name': 'name',
        'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'pendingAdmin': {
        'constant': True,
        'inputs': [],
        'name': 'pendingAdmin',
        'outputs': [
            {'internalType': 'address payable', 'name': '', 'type': 'address'}
        ],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'redeem': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'redeemTokens',
                'type': 'uint256',
            }
        ],
        'name': 'redeem',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'redeemUnderlying': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'redeemAmount',
                'type': 'uint256',
            }
        ],
        'name': 'redeemUnderlying',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'repayBorrow': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'uint256',
                'name': 'repayAmount',
                'type': 'uint256',
            }
        ],
        'name': 'repayBorrow',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'repayBorrowBehalf': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'borrower', 'type': 'address'},
            {
                'internalType': 'uint256',
                'name': 'repayAmount',
                'type': 'uint256',
            },
        ],
        'name': 'repayBorrowBehalf',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'reserveFactorMantissa': {
        'constant': True,
        'inputs': [],
        'name': 'reserveFactorMantissa',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'seize': {
        'constant': False,
        'inputs': [
            {
                'internalType': 'address',
                'name': 'liquidator',
                'type': 'address',
            },
            {'internalType': 'address', 'name': 'borrower', 'type': 'address'},
            {
                'internalType': 'uint256',
                'name': 'seizeTokens',
                'type': 'uint256',
            },
        ],
        'name': 'seize',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'supplyRatePerBlock': {
        'constant': True,
        'inputs': [],
        'name': 'supplyRatePerBlock',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'symbol': {
        'constant': True,
        'inputs': [],
        'name': 'symbol',
        'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'totalAdminFees': {
        'constant': True,
        'inputs': [],
        'name': 'totalAdminFees',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'totalBorrows': {
        'constant': True,
        'inputs': [],
        'name': 'totalBorrows',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'totalBorrowsCurrent': {
        'constant': False,
        'inputs': [],
        'name': 'totalBorrowsCurrent',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'totalFuseFees': {
        'constant': True,
        'inputs': [],
        'name': 'totalFuseFees',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'totalReserves': {
        'constant': True,
        'inputs': [],
        'name': 'totalReserves',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'totalSupply': {
        'constant': True,
        'inputs': [],
        'name': 'totalSupply',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'transfer': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'dst', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
        ],
        'name': 'transfer',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'transferFrom': {
        'constant': False,
        'inputs': [
            {'internalType': 'address', 'name': 'src', 'type': 'address'},
            {'internalType': 'address', 'name': 'dst', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
        ],
        'name': 'transferFrom',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    'underlying': {
        'constant': True,
        'inputs': [],
        'name': 'underlying',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
}


interest_rate_model_function_abis = {
    'baseRatePerBlock': {
        'constant': True,
        'inputs': [],
        'name': 'baseRatePerBlock',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'blocksPerYear': {
        'constant': True,
        'inputs': [],
        'name': 'blocksPerYear',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'getBorrowRate': {
        'constant': True,
        'inputs': [
            {'internalType': 'uint256', 'name': 'cash', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'borrows', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'reserves', 'type': 'uint256'},
        ],
        'name': 'getBorrowRate',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'getSupplyRate': {
        'constant': True,
        'inputs': [
            {'internalType': 'uint256', 'name': 'cash', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'borrows', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'reserves', 'type': 'uint256'},
            {
                'internalType': 'uint256',
                'name': 'reserveFactorMantissa',
                'type': 'uint256',
            },
        ],
        'name': 'getSupplyRate',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'isInterestRateModel': {
        'constant': True,
        'inputs': [],
        'name': 'isInterestRateModel',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'jumpMultiplierPerBlock': {
        'constant': True,
        'inputs': [],
        'name': 'jumpMultiplierPerBlock',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'kink': {
        'constant': True,
        'inputs': [],
        'name': 'kink',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'multiplierPerBlock': {
        'constant': True,
        'inputs': [],
        'name': 'multiplierPerBlock',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'view',
        'type': 'function',
    },
    'utilizationRate': {
        'constant': True,
        'inputs': [
            {'internalType': 'uint256', 'name': 'cash', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'borrows', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'reserves', 'type': 'uint256'},
        ],
        'name': 'utilizationRate',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'payable': False,
        'stateMutability': 'pure',
        'type': 'function',
    },
}

